---
- name: Create admin users
  ansible.builtin.user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    groups: "smclnx"
    shell: /bin/bash
  loop: "{{ admin_users }}"

- name: Configure sudoers for admin users
  ansible.builtin.copy:
    dest: /etc/sudoers.d/smclnx
    content: |
      %smclnx ALL=(ALL) NOPASSWD: ALL
  validate: 'visudo -cf %s'
