- name: Create admin users
  ansible.builtin.user:
    name: "{{ item.username }}"
    password: "{{ item.password | password_hash('sha512') }}"
    groups: "admins"
    shell: /bin/bash
  loop: "{{ admin_users }}"

- name: Configure sudoers for admin users
  ansible.builtin.copy:
    dest: /etc/sudoers.d/admins
    content: |
      %admins ALL=(ALL) NOPASSWD: ALL
  validate: 'visudo -cf %s'
