---
- name: Create system users
  ansible.builtin.user:
    name: "{{ item.username }}"
    password: "{{ 'password123' | password_hash('sha512') }}"
    groups: "smclnx"
    shell: /bin/bash
  loop: "{{ system_users }}"